export const LANGUAGE_VERSIONS = {
  "c++": "10.2.0",
  java: "15.0.2",
  python2: "2.7.18",
  python: "3.10.0",
  c: "10.2.0",
  typescript: "5.0.3",
};

export const language_ID = {
  assembly: 45,
  bash: 46,
  basic: 47,
  "c-clang": 104,
  "c-clang-7": 75,
  "c++-clang": 76,
  "c": 103,
  "c++": 105,
  "c-gcc-7": 48,
  "c++-gcc-7": 52,
  "c-gcc-8": 49,
  "c++-gcc-8": 53,
  "c-gcc-9": 50,
  "c++-gcc-9": 54,
  clojure: 86,
  "c#": 51,
  cobol: 77,
  "common-lisp": 55,
  dart: 90,
  d: 56,
  elixir: 57,
  erlang: 58,
  executable: 44,
  "f#": 87,
  fortran: 59,
  "go-1.13": 60,
  "go-1.18": 95,
  groovy: 88,
  haskell: 61,
  javafx: 96,
  java: 91,
  "java-openjdk": 62,
  "js-node-12": 63,
  "js-node-18": 93,
  "js-node-20": 97,
  "js-node-22": 102,
  kotlin: 78,
  lua: 64,
  "multi-file": 89,
  "objective-c": 79,
  ocaml: 65,
  octave: 66,
  pascal: 67,
  perl: 85,
  "php-7": 68,
  "php-8": 98,
  "plain-text": 43,
  "prolog": 69,
  "python2": 70,
  "python-3.11": 92,
  "python": 100,
  "python-3.8": 71,
  "r-4.0": 80,
  "r-4.4": 99,
  ruby: 72,
  rust: 73,
  scala: 81,
  sql: 82,
  swift: 83,
  "typescript-3.7": 74,
  "typescript-5": 94,
  "typescript": 101,
  "visual-basic-net": 84
};

export const CODE_SNIPPETS = {
  "c++":
    '#include <iostream>\nint main() {\n    std::cout << "Hello, World!";\n    return 0;\n}',
  java: 'public class HelloWorld {\n    public static void main(String[] args) {\n        System.out.println("Hello, World!");\n    }\n}',
  python2: 'print "Hello, World!"',
  python: 'print("Hello, World!")',
  c: '#include <stdio.h>\nint main() {\n    printf("Hello, World!\\n");\n    return 0;\n}',
  csharp:
    'using System;\nclass HelloWorld {\n    static void Main() {\n        Console.WriteLine("Hello, World!");\n    }\n}',
  javascript: 'console.log("Hello, World!");',
  typescript: 'console.log("Hello, World!");',
};

const localhost = `https://cp-buddy-4ngv.onrender.com`;

export const routes = {
  localhost,
  questionroute: `${localhost}/api/questions`,
  getroute: `${localhost}/api/getcode`,
};
